### ISSUE TITLE
upload a small video demo

### ISSUE THREAD

**Issue by dumkar** [menegolli/Quantum_synth#4]
I like your presentation at Qiskit Camp and like to show to other people what you have made! Would you be able to make & upload a small video where you show the synth in action?

**Comment by menegolli** [comment]
Dear @dumkar 
I have just created a directory for storing demo videos (the ones we have shown during the final presentation).
Is this ok for you?

I guess we will also make other ones in the future!

**Comment by dumkar** [comment]
Cool, thanks!
